spring:
  datasource:
      driver-class-name: ${driver}
      url: ${url}
      username: ${username}
      password: ${password}
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/musinsa
#    username: sa
#    password:

  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql: trace